dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: WyGwwFHd3U+iN2SX8L3bvEhj8HZ8rTTJ7KNsAO3SRsYGas9wOEPjVMnA8yR+WtXb9Bszth1X1D2zywdi1P+PviY5+JuFMZajQTuXXvIC59ONBZ84KY+sI8qF4b8S/YWOoQvhF9dF+CT98iQo3KVVRZJ8kAPADl1EoA4uGSVKNvQLcS4XFVfR/ICb4joEX3ZGKW/WrA+x2Lbg079iOqdPahwiY9BSTx7PELIuZArp/EKvkvkEGLRkkUYt6/Tjvx0YOt5OaYvIxsDlUXcaOHxcHNMhMNt87ZLM7u0eJZ5xNHkvEKrBKcfYdd2vIdqmbGbU8sv1PV/S0POQAoviuk4zDJWTDlvEmMhZpxTCIu3ItV9zBd51qJCGUg1eborwFAja78gyBwYO6bsQkxW8Z16ZRVo1i6Nfj+twlp27mJ2FLRQeqisZER5h8AV62Y3+QPVJOwfzBcJ4A5EZHVyljkLgYS8uJn6ZkDPPQu0v+Str+xNqe56+IbeRqy/mZis6hkWHA5m4TuLIsQWw+s4mD4At76ucH/alk8XlizSdyNfaBWyG1vaIU+vfcSiLEhJfLMUo9vZ4yptlg1AkpD9OejlWrqlIMxZ1Vn4DFlpYlY7VeBDtV5xjzMtphwIjwwmyHG/Elc6ynH6t+4lUlLloQiJU6Qass/pl92p29aRb1fISvEY=
  - secure: s4pWcP9h5q5ZB+iHBNedQO09Am4xQnVbpghuyDTtdOPNEGva7gVIQ6BmYHyw+hHamXRVK4PM+bi7ooTH5TpcOhqfPGeCCm48wNjpJH0Dtr03bi+XecLaaez/6AGh6mJ6pgTsON18yHPgEb8zYspL/pMtdvX3G2B9yBgL5F731sPTy4nPWWi0SjyRyKMzN/Ae2UzucOLUChNaHAZJ/hdsbze+wAbZKGdqT7RX1id/4Ar/jfxqu4Kj1HD1WX8UZ1oBHYLt7iVgi2B1LpUYEEaY6Ti+Lc3MmJFz1dTVD2SJg61Y0+XWe8FblO/T+FYy/JvPUJxTz4VABjJL+pwxnOir9WMxEU7K9anKUTY7Kmd713qSFkEeveMlETWP8JKKeHnZvPTvTvrEIefJXJOcm7y3+BJ0WCxIz6v7KAmYFWzb+Vv05cPfp7VvS1i6HE69xcN3lY8Dlb6vpyDmtXh8jtugnMSn/ghj8yg2nOixtJNPAzUsqbbj7aPsedhHk90JT+D6D+oZaPbIcR/wToft+yL7dFUxKc9IEAcqZoABniXe7rehoo33jNKZPqAuKa+c98wkNvTPv2OsOoazPGTI9rfU2XjRD1jhi35scibVbZmCVx21BCzQH5W5Xaw9M35PDuEzljSk7y2D5sOFnj3/R3EzT6zPKEQn0RvznIJ/cbibyb4=
  - secure: NfppO25fCI9SivXR4K1uXwXVJlfEcj23gYPoPo4Ue4blh3cKvop8p+VoowA1J/4uPQr4Avkf6rdqnBV4tUTond07JpRsSkRRc5pRmhphVrwKS+ac/1CZCu1IREbjwQxdOikSiejISa4QdiGPLMSP+j0haEY9xs6pbovxCSqoamjLUrOSjF3TN6V4z3Ei8MUrcATWqiKJGQQhxR8FLC0Oj/eZiUmaGvafndMIXHmB0alTzPkDnIPF1TB28Y7EkkdRd2SipphtHF3JvczrjgmEkc/z9ulglMQ/CdpTv2x5gtkk+44ofNjHpmo7gGZmJapspvBla5lRZ+iUz/LeWkXe9h+j611nWc6WvLZ0sGftrNj1OPlSmCPITohkcSMWKxyYkj8ztox9pcPUj0O1U5nsTMk+KxpH/ycrox+5N+L7QYacwtNweEAirJSs66ak8XC+7s5io6vf/6J0TX/GpkiGBdsGYpI/yCbu1EpG2v4qLndnyzVfjPwpHV8TMq12arc/py5ALzLtz56lwLh/D6kvpLiFxRZMG0FhwBnA0or+M+43Mb0sPf7WjtL8uJ3DS+iraO4+yvLSRZmIKdBoJQiqZYtte3glJBpYLRF5KrhJ9OPD3/3XeHCFYUCVUF4N8pSW81e4ITIufzuGJauLcuBjVj7LUAcZmKitrM6Ziwdlqt8=
addons:
  apt:
    packages:
    - openssl
    - gnupg
install: true
script: bash travis-build.bash
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
before_install:
- openssl aes-256-cbc -K $encrypted_de282c3465e2_key -iv $encrypted_de282c3465e2_iv
  -in atomist_sec.gpg.enc -out atomist_sec.gpg -d
deploy:
  provider: releases
  api_key:
    secure: LfwAthEa2oFq+Gw0W1xBrw8fxix0j/GblnQSD/rQ3FT1LcXLWpqPo5WVuiAekStskvaWWLxpvyplYGEo/6e//7DGai8tvRrUBthGQT8R40cc7vwcyYWRd56T8oeSU5IQgmYZSfTdIETlO06g0RI9yaZAn2IjyGiuM22czIFCgEc2ZzB2fyHcJLF7wWKhZQhqJewBda8xzQEHK6dwBF/YTWccpOl2W0lDM6CpbppvwCssuL+fIlsep84ZQhNOmHb4icXk5AvAD1r7Xp+tOpSd9kFVYMsIhmAVCfsk0C5xczFF695s2g9dYd+RJS2nk3L8usrUjJD/uDlxi1kXMdi6y1V6ZK9p2NBODnUwHfx78TeKhr9s7nob2pZ6DVEEGf2xXjhLzQ/gJq8pphSaJAgy2P/gpuU9CHv53jp5I8d/9CFwJ0vKBHjJjoIoSNnFhf07VMRCx0wu/UNTMDFMGzhu3SzM3B4UhVuZHPfKoCbWdDXrGjqTZ5r0ke1Czdlrf/jpu8Dg92dSh7jk0Ko1OzUOGY5R3x7/er93kVLUNP+C2B1KiUbSip7z2fs7yLV7a19T/oPEUV4ctrJsOsSexocp/hjGgo1TubmfO//luzdxBq53KJ2mVUaf+cpwvfWj1o4yR+f7Td2nVZVR2vf9BfdnQZodiDHiH2ELFfVHC4Ku5go=
  on:
      tags: true
      condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
